import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

// Simplified presentation-full route that just uses outline data
export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { outlines, template = 'modern', prompt } = body;

    if (!outlines || !Array.isArray(outlines)) {
      return NextResponse.json(
        { error: 'Missing or invalid outlines' },
        { status: 400 }
      );
    }

    console.log('✨ Processing presentation with existing outline data...');
    console.log(`📊 Found ${outlines.length} slides with images`);

    // Simply transform the outlines into the final slide format
    // No need to regenerate anything - we already have everything!
    const slides = outlines.map((outline: any, index: number) => {
      return {
        title: outline.title || `Slide ${index + 1}`,
        content: outline.content || outline.description || '',
        bullets: outline.bullets || outline.bulletPoints || [],
        charts: outline.chartData || null,
        // CRITICAL: Use the image from outline (already generated by FLUX)
        image: outline.image || outline.imageUrl || `https://placehold.co/1024x576/EEE/31343C?text=Slide+${index + 1}`,
        layout: outline.layout || outline.type || 'title-content',
        imagePrompt: outline.imageQuery || outline.imagePrompt || ''
      };
    });

    console.log(`✅ Processed ${slides.length} slides successfully`);
    console.log(`🖼️ All slides have images: ${slides.every(s => s.image) ? 'YES' : 'NO'}`);

    return NextResponse.json({ slides });
  } catch (error) {
    console.error('Error processing presentation:', error);
    return NextResponse.json(
      { error: 'Failed to process presentation' },
      { status: 500 }
    );
  }
}